#define I2C_IN_STARTED_UP 0
#define I2C_IN_ONLINE 1
#define I2C_IN_OFFLINE 2
#define I2C_IN_RFID 3
#define I2C_IN_ADD_POINT 4
#define I2C_IN_REMOVE_POINT 5
#define I2C_IN_RESET 6

#define I2C_OUT_STARTUP 0
#define I2C_OUT_ENABLE 1
#define I2C_OUT_PLAYER 2
#define I2C_OUT_GOAL 3
#define I2C_OUT_WIN 4
#define I2C_OUT_LOSS 5
#define I2C_OUT_GAME_STARTED 6
#define I2C_OUT_CONNECTION_LOST 7
#define I2C_OUT_RECONNECTED 8
#define I2C_OUT_TEMP_PLAYER 9
#define I2C_OUT_OFFLINE 10
#define I2C_OUT_END 11

#define I2C_OUT_ERROR_WIFI 12